version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: vacancies_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: postgres
       - TZ=Asia/Yekaterinburg
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/schemas
    restart: always

  mcp:
    image: crystaldba/postgres-mcp
    container_name: postgres-mcp
    ports:
      - "8080:8080"
    environment:
      - MCP_CONFIG=/config/mcp.yaml        # оставьте, если нужно
      - DATABASE_URI=postgresql://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}
    volumes:
      - ./config:/config
    depends_on:
      - postgres

  app:
    build: .
    container_name: vacancies_app
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./backups:/backups          # монтируем локальную папку для хранения JSON
      - ./scripts:/scripts          # (опционально) если скрипт лежит в scripts/
    restart: unless-stopped
    command: >
      sh -c "
      while true; do
        python main.py;
        sleep 3600;
      done
      "

volumes:
  pg_data:
